[package]
name = "cjdns"
version = "0.1.0"
description = "Admin API implementation of cjdns"
license = "LGPL-3.0"
repository = "https://github.com/kpcyrd/cjdns-rs"
authors = ["kpcyrd <git@rxv.cc>"]

[dependencies]
bencode = "0.1.16"
rustc-serialize = "0.3"
